### ISSUE TITLE
Verify that the streamlined onboarding components are on the pis (and starting)

### ISSUE THREAD

**Issue by craigpratt** [cablelabs/Streamlined_Onboarding_Demo#8]
(and automatically starting)

**Comment by adolan5** [comment]
Final status on this:
* AP has a `diplomat.service` that invokes the diplomat.
  * Its credentials are located at `/var/local/streamlined_onboarding/dpp_diplomat_creds`
* Client Pis (sopi2 & sopi3/soblue) have XDG autostart files installed at `/home/pi/.config/autostart`
  * These invoke the Python module's main script for the lightswitch or lamp
  * Any of those `.desktop` files that have `Hidden=true` are disabled
* `wpa_supplicant` is currently a symlink to `/usr/local/bin/streamlined_onboarding/wpa_supplicant`
  * This is the binary that is run by default on the client Pis using `dhcpcd`
